const demo={
teams:[
{id:"D",name:"Team D",captain:"",players:[{id:"d1",name:"Jitendra",gender:"M"},{id:"d2",name:"Nishant",gender:"M"},{id:"d3",name:"Yamini",gender:"F"},{id:"d4",name:"Tejashree",gender:"F"}]},
{id:"E",name:"Team E",captain:"",players:[{id:"e1",name:"Amit",gender:"M"},{id:"e2",name:"Rahul",gender:"M"},{id:"e3",name:"Reshma",gender:"F"},{id:"e4",name:"Yogeshwari",gender:"F"}]}],
matches:[
{id:"m1",time:"7:30",court:"1",type:"Women's Doubles",a:"D",b:"E",ap:["d3","d4"],bp:["e3","e4"],status:"live",game:0,sets:[[18,17],[0,0],[0,0]],history:[]},
{id:"m2",time:"7:40",court:"2",type:"Men's Doubles",a:"D",b:"E",ap:["d1","d2"],bp:["e1","e2"],status:"upcoming",game:0,sets:[[0,0],[0,0],[0,0]],history:[]}]};
let state={mode:"demo",data:JSON.parse(JSON.stringify(demo))}, sb=null;
const cfg=window.PCBL_CONFIG||{};
if(cfg.SUPABASE_URL&&cfg.SUPABASE_PUBLISHABLE_KEY) sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
const $=id=>document.getElementById(id);
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function show(page){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$(page).classList.remove("hidden");document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===page));render()}
function useDemo(){state.mode="demo";$("loginView").classList.add("hidden");$("mainView").classList.remove("hidden");$("connection").textContent="LOCAL DEMO";render()}
async function logout(){if(sb) await sb.auth.signOut();location.reload()}
async function boot(){
 if(!sb){return}
 const {data:{session}}=await sb.auth.getSession();
 if(session){state.mode="cloud";$("loginView").classList.add("hidden");$("mainView").classList.remove("hidden");$("connection").textContent="SUPABASE";$("connection").classList.add("ok");await loadCloud();subscribe()}
}
$("loginForm").onsubmit=async e=>{e.preventDefault();if(!sb){$("loginMsg").textContent="Add Supabase URL/key in config.js, or use demo mode.";return}let {error}=await sb.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(error)$("loginMsg").textContent=error.message;else location.reload()}
function team(id){return state.data.teams.find(t=>t.id===id)}
function player(id){for(const t of state.data.teams){let p=t.players.find(p=>p.id===id);if(p)return p}}
function render(){
 $("stats").innerHTML=`<div class="stat"><span>Teams</span><strong>${state.data.teams.length}</strong></div><div class="stat"><span>Players</span><strong>${state.data.teams.reduce((n,t)=>n+t.players.length,0)}</strong></div><div class="stat"><span>Matches</span><strong>${state.data.matches.length}</strong></div><div class="stat"><span>Live Courts</span><strong>${state.data.matches.filter(m=>m.status==="live").length}</strong></div>`;
 $("playerTeam").innerHTML=state.data.teams.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join("");
 $("teamCards").innerHTML=state.data.teams.map(t=>`<div class="teamcard"><div class="teamtitle"><h2>${esc(t.name)}</h2><span>${t.players.length} players</span></div><p class="muted">Captain: ${esc(t.captain||"—")}</p>${t.players.map(p=>`<div class="player">${esc(p.name)} <span class="gender">${p.gender==="F"?"♀ Female":"♂ Male"}</span></div>`).join("")}</div>`).join("");
 $("fixturesBody").innerHTML=state.data.matches.map(m=>{let a=team(m.a),b=team(m.b);let ap=m.ap.map(id=>player(id)?.name).filter(Boolean).join(" & "),bp=m.bp.map(id=>player(id)?.name).filter(Boolean).join(" & ");return `<tr><td>${m.time||"—"}</td><td>${esc(m.court||"—")}</td><td>${esc(m.type)}</td><td>${esc(a?.name)}</td><td>${esc(b?.name)}</td><td>${esc(ap)} vs ${esc(bp)}</td><td>${m.status}</td><td>${m.status!=="done"?`<button class="btn small" onclick="startMatch('${m.id}')">Score</button>`:"✓"}</td></tr>`}).join("");
 $("liveGrid").innerHTML=state.data.matches.filter(m=>m.status==="live").map(court).join("")||'<div class="card"><b>No live matches.</b><p class="muted">Start a fixture from Fixtures.</p></div>';
 $("standings").innerHTML=state.data.teams.map(t=>{let wins=state.data.matches.filter(m=>m.status==="done"&&winner(m)===t.id).length;return `<div class="player"><b>${esc(t.name)}</b><b>${wins}</b></div>`}).join("");
 $("schedule").innerHTML=state.data.matches.slice().sort((a,b)=>(a.time||"").localeCompare(b.time||"")).map(m=>`<div class="player"><span><b>${esc(m.time||"—")}</b> · Court ${esc(m.court||"—")}<br>${esc(m.type)} · ${esc(team(m.a)?.name)} vs ${esc(team(m.b)?.name)}</span><span>${m.status}</span></div>`).join("");
}
function winner(m){let a=0,b=0;(m.sets||[]).forEach(s=>{if(Math.max(...s)>=21&&Math.abs(s[0]-s[1])>=2||Math.max(...s)>=30){if(s[0]>s[1])a++;else if(s[1]>s[0])b++}});return a>b?m.a:b>a?m.b:null}
function court(m){let a=team(m.a),b=team(m.b),s=m.sets[m.game]||[0,0],ga=(m.sets||[]).filter(x=>x[0]>x[1]&&Math.max(...x)>=21).length,gb=(m.sets||[]).filter(x=>x[1]>x[0]&&Math.max(...x)>=21).length;return `<div class="court"><div class="courthead"><div><b>Court ${esc(m.court)}</b><div style="color:#9ca3af">${esc(m.type)} · ${esc(m.time)}</div></div><span class="livepill">● LIVE</span></div><div class="scoreteams"><div class="side"><div class="names">${esc(a.name)}<br><small>${m.ap.map(id=>esc(player(id)?.name||"")).join(" & ")}</small></div><button class="scorebtn" onclick="point('${m.id}','A')">${s[0]}</button></div><div class="center"><strong>–</strong><div class="games">Games ${ga} : ${gb}</div></div><div class="side"><div class="names">${esc(b.name)}<br><small>${m.bp.map(id=>esc(player(id)?.name||"")).join(" & ")}</small></div><button class="scorebtn" onclick="point('${m.id}','B')">${s[1]}</button></div></div><div class="courtActions"><button class="btn" onclick="undo('${m.id}')">↶ Undo</button> <button class="btn" onclick="finish('${m.id}')">Finish</button></div></div>`}
function startMatch(id){let m=state.data.matches.find(x=>x.id===id);m.status="live";if(state.mode==="cloud") saveCloudMatch(m);else render();show("live")}
function point(id,side){let m=state.data.matches.find(x=>x.id===id);if(!m)return;if(state.mode==="cloud"){cloudPoint(id,side);return}m.history.push({sets:JSON.parse(JSON.stringify(m.sets)),game:m.game,status:m.status});m.sets[m.game][side==="A"?0:1]++;advance(m);render()}
function advance(m){let s=m.sets[m.game],a=s[0],b=s[1];if((Math.max(a,b)>=21&&Math.abs(a-b)>=2)||Math.max(a,b)>=30){m.game++;if(m.game>=3||m.sets.filter(s=>((Math.max(...s)>=21&&Math.abs(s[0]-s[1])>=2)||Math.max(...s)>=30)&&s[0]!==s[1]).length>=2)m.status="done";else{m.game=Math.min(m.game,2)}}}
async function cloudPoint(id,side){let {error}=await sb.rpc("add_point",{p_match:id,p_side:side});if(error)alert(error.message)}
function undo(id){let m=state.data.matches.find(x=>x.id===id);if(state.mode==="cloud"){alert("For cloud scoring, use the database event log for audited corrections.");return}let h=m.history.pop();if(h){m.sets=h.sets;m.game=h.game;m.status=h.status;render()}}
function finish(id){let m=state.data.matches.find(x=>x.id===id);m.status="done";if(state.mode==="cloud")saveCloudMatch(m);else render()}
$("teamForm").onsubmit=e=>{e.preventDefault();let name=$("teamName").value.trim();if(state.mode==="cloud")addCloudTeam(name,$("captain").value.trim());else{state.data.teams.push({id:"t"+Date.now(),name,captain:$("captain").value.trim(),players:[]});e.target.reset();render()}}
$("playerForm").onsubmit=e=>{e.preventDefault();let t=team($("playerTeam").value),p={id:"p"+Date.now(),name:$("playerName").value.trim(),gender:$("gender").value};if(state.mode==="cloud")addCloudPlayer(t.id,p);else{t.players.push(p);e.target.reset();render()}}
function openMatchModal(){let opts=state.data.teams.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join("");$("modalBox").innerHTML=`<h2>Add PCBL Match</h2><div class="two"><input id="mtTime" placeholder="Time e.g. 7:30"><input id="mtCourt" placeholder="Court"><select id="mtType"><option>Men's Singles</option><option>Women's Singles</option><option>Men's Doubles</option><option>Women's Doubles</option><option>Mixed Doubles</option></select><select id="mtA">${opts}</select><select id="mtB">${opts}</select></div><div class="lineup"><div><h3>Team A lineup</h3><div id="lineA" class="checks"></div></div><div><h3>Team B lineup</h3><div id="lineB" class="checks"></div></div></div><div id="lineMsg" class="warn"></div><div style="text-align:right;margin-top:14px"><button class="btn" onclick="closeModal()">Cancel</button> <button class="btn dark" onclick="createMatch()">Create Match</button></div>`;$("modal").classList.remove("hidden");populateLineups();$("mtA").onchange=populateLineups;$("mtB").onchange=populateLineups}
function populateLineups(){if(!$("lineA"))return;let A=team($("mtA").value),B=team($("mtB").value);$("lineA").innerHTML=A.players.map(p=>`<label><input type="checkbox" value="${p.id}">${esc(p.name)} (${p.gender})</label>`).join("");$("lineB").innerHTML=B.players.map(p=>`<label><input type="checkbox" value="${p.id}">${esc(p.name)} (${p.gender})</label>`).join("")}
function createMatch(){let a=$("mtA").value,b=$("mtB").value;if(a===b)return alert("Choose different teams.");let ap=[...document.querySelectorAll("#lineA input:checked")].map(x=>x.value),bp=[...document.querySelectorAll("#lineB input:checked")].map(x=>x.value);if(ap.length<1||bp.length<1)return alert("Select players for both teams.");let m={id:"m"+Date.now(),time:$("mtTime").value,court:$("mtCourt").value,type:$("mtType").value,a,b,ap,bp,status:"upcoming",game:0,sets:[[0,0],[0,0],[0,0]],history:[]};if(state.mode==="cloud")addCloudMatch(m);else{state.data.matches.push(m);closeModal();render()}}
function closeModal(){$("modal").classList.add("hidden")}
async function loadCloud(){let [tt,pp,mm,mp,gg]=await Promise.all([sb.from("teams").select("*"),sb.from("players").select("*"),sb.from("matches").select("*"),sb.from("match_players").select("*"),sb.from("games").select("*")]);if(tt.error){console.error(tt.error);return}state.data={teams:(tt.data||[]).map(t=>({...t,players:(pp.data||[]).filter(p=>p.team_id===t.id).map(p=>({...p,id:p.id}))})),matches:(mm.data||[]).map(m=>{let g=(gg.data||[]).filter(x=>x.match_id===m.id).sort((a,b)=>a.game_no-b.game_no);return {...m,id:m.id,a:m.team_a,b:m.team_b,ap:(mp.data||[]).filter(x=>x.match_id===m.id&&x.side==="A").map(x=>x.player_id),bp:(mp.data||[]).filter(x=>x.match_id===m.id&&x.side==="B").map(x=>x.player_id),game:(m.current_game||1)-1,sets:[1,2,3].map(n=>{let x=g.find(z=>z.game_no===n);return x?[x.score_a,x.score_b]:[0,0]}),history:[]})})};render()}
function subscribe(){sb.channel("pcbl-live").on("postgres_changes",{event:"*",schema:"public",table:"games"},loadCloud).on("postgres_changes",{event:"*",schema:"public",table:"matches"},loadCloud).subscribe()}
async function saveCloudMatch(m){await sb.from("matches").update({status:m.status,current_game:(m.game||0)+1}).eq("id",m.id);await loadCloud()}
async function addCloudTeam(name,captain){let {data,error}=await sb.from("teams").insert({name,captain}).select().single();if(error)alert(error.message);else{await loadCloud();$("teamForm").reset()}}
async function addCloudPlayer(team_id,p){let {error}=await sb.from("players").insert({team_id,name:p.name,gender:p.gender});if(error)alert(error.message);else{await loadCloud();$("playerForm").reset()}}
async function addCloudMatch(m){let {data,error}=await sb.from("matches").insert({match_no:state.data.matches.length+1,scheduled_at:null,court:m.court,match_type:m.type,team_a:m.a,team_b:m.b,status:"upcoming",current_game:1}).select().single();if(error){alert(error.message);return}await sb.from("match_players").insert([...m.ap.map(id=>({match_id:data.id,player_id:id,side:"A"})),...m.bp.map(id=>({match_id:data.id,player_id:id,side:"B"}))]);await sb.from("games").insert({match_id:data.id,game_no:1});closeModal();await loadCloud()}
boot();