import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { SUPABASE_URL, SUPABASE_ANON_KEY } from './config.js';
const sb=createClient(SUPABASE_URL,SUPABASE_ANON_KEY);let tournament,teams=[],matches=[],role='public',score={a:0,b:0};
const $=id=>document.getElementById(id), teamMap=()=>Object.fromEntries(teams.map(t=>[t.id,t]));
function timeKey(s){const [x,ap]=s.split(' ');let [h,m]=x.split(':').map(Number);if(ap==='PM'&&h!==12)h+=12;if(ap==='AM'&&h===12)h=0;return h*60+m}
function show(p){document.querySelectorAll('main section').forEach(s=>s.classList.add('hidden'));$(p).classList.remove('hidden');document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.p===p))}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.p));
function row(m){let tm=teamMap(),title=m.match_type==='backup'?'⏱ BACKUP TIME':m.match_type==='final'?'🏆 FINALS':`${tm[m.team1_id]?.code||'TBD'} vs ${tm[m.team2_id]?.code||'TBD'}`;return `<div class="match"><span>${m.start_time} – ${m.end_time}</span><b class="${m.match_type==='backup'?'backup':''}">${title}</b><span class="badge ${m.status}">${m.status.toUpperCase()}</span></div>`}
function render(){let sat=matches.filter(m=>m.match_day==='Saturday').sort((a,b)=>timeKey(a.start_time)-timeKey(b.start_time)),sun=matches.filter(m=>m.match_day==='Sunday').sort((a,b)=>timeKey(a.start_time)-timeKey(b.start_time));$('sat').innerHTML=sat.map(row).join('');$('sun').innerHTML=sun.map(row).join('');$('next').innerHTML=matches.filter(m=>m.status==='scheduled'&&m.match_type==='league').slice(0,5).map(row).join('')||'<span class="muted">No upcoming matches.</span>';$('liveCount').textContent=matches.filter(m=>m.status==='live').length;let playable=matches.filter(m=>m.match_type!=='backup');$('matchSelect').innerHTML=playable.map(m=>{let t=teamMap();return `<option value="${m.id}">${m.match_day} • ${m.start_time} • ${m.match_type==='final'?'FINALS':`${t[m.team1_id]?.code||'TBD'} vs ${t[m.team2_id]?.code||'TBD'}`}</option>`}).join('');renderTeams();standings();selectLive()}
function selectLive(){let m=matches.find(x=>x.id===$('matchSelect').value);if(!m)return;score={a:m.score1,b:m.score2};$('sa').textContent=score.a;$('sb').textContent=score.b;$('state').value=m.status==='backup'?'scheduled':m.status;let t=teamMap();$('liveTeams').textContent=m.match_type==='final'?`FINALS: ${t[m.team1_id]?.code||'TBD'} vs ${t[m.team2_id]?.code||'TBD'}`:`TEAM ${t[m.team1_id]?.code||''} vs TEAM ${t[m.team2_id]?.code||''}`}
$('matchSelect').onchange=selectLive;document.querySelectorAll('[data-score]').forEach(b=>b.onclick=()=>{if(!['admin','scorekeeper'].includes(role))return msg('Scorekeeper or Admin access required.');let [i,n]=b.dataset.score.split(',').map(Number);if(i===0)score.a=Math.max(0,score.a+n);else score.b=Math.max(0,score.b+n);$('sa').textContent=score.a;$('sb').textContent=score.b});
$('publish').onclick=async()=>{if(!['admin','scorekeeper'].includes(role))return msg('Scorekeeper or Admin access required.');let {error}=await sb.rpc('publish_score',{p_match:$('matchSelect').value,p_score1:score.a,p_score2:score.b,p_status:$('state').value});msg(error?error.message:'Published live.');if(!error)await load()};function msg(x){$('scoreMsg').textContent=x;$('scoreMsg').className='ok'}
function standings(){let t=Object.fromEntries(teams.map(x=>[x.id,{...x,w:0,l:0,pf:0,pa:0,lp:0}]));matches.filter(m=>m.match_type==='league'&&m.status==='completed').forEach(m=>{let a=t[m.team1_id],b=t[m.team2_id];if(!a||!b)return;a.pf+=m.score1;a.pa+=m.score2;b.pf+=m.score2;b.pa+=m.score1;if(m.score1>m.score2){a.w++;a.lp+=2;b.l++}else if(m.score2>m.score1){b.w++;b.lp+=2;a.l++}});let q=Object.values(t).sort((a,b)=>b.lp-a.lp||b.w-a.w||(b.pf-b.pa)-(a.pf-a.pa)||b.pf-a.pf);$('stand').innerHTML=`<table><thead><tr><th>#</th><th>Team</th><th>Captain</th><th>W</th><th>L</th><th>PF</th><th>PA</th><th>Diff</th><th>LP</th></tr></thead><tbody>${q.map((x,i)=>`<tr><td>${i+1}</td><td>${x.name}</td><td>${x.captain_name||''}</td><td>${x.w}</td><td>${x.l}</td><td>${x.pf}</td><td>${x.pa}</td><td>${x.pf-x.pa}</td><td><b>${x.lp}</b></td></tr>`).join('')}</tbody></table>`}
function renderTeams(){$('teamCards').innerHTML=teams.sort((a,b)=>a.code.localeCompare(b.code)).map(t=>`<div class="card"><div class="metric">TEAM ${t.code}</div><h2>${t.captain_name||''}</h2><div class="muted">${t.name}</div></div>`).join('')}
async function load(){let r=await Promise.all([sb.from('tournaments').select('*').limit(1),sb.from('teams').select('*'),sb.from('matches').select('*')]);if(r.some(x=>x.error)){ $('connection').textContent=r.find(x=>x.error)?.error.message||'Database error';return }tournament=r[0].data?.[0];teams=r[1].data||[];matches=r[2].data||[];render();$('connection').innerHTML='<span class="ok">● Connected to Supabase Realtime</span>'}
async function auth(){let {data:{session}}=await sb.auth.getSession();if(!session){let email=prompt('Enter your email for a magic sign-in link:');if(email){let {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:location.href}});alert(error?error.message:'Check your email for the sign-in link.')}return}let p=await sb.from('profiles').select('display_name,role').eq('id',session.user.id).maybeSingle();role=p.data?.role||'public';$('userLabel').textContent=`${p.data?.display_name||session.user.email} • ${role}`;$('authBtn').classList.add('hidden');$('signOutBtn').classList.remove('hidden')}
$('authBtn').onclick=auth;$('signOutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};
await auth();await load();sb.channel('pcbl-live').on('postgres_changes',{event:'*',schema:'public',table:'matches'},load).on('postgres_changes',{event:'*',schema:'public',table:'score_events'},load).subscribe();
