(() => {
  const cfg=window.PCBL_CONFIG||{}; let sb=null; let tournament=null; let teams=[]; let players=[];
  const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  function team(id){return teams.find(t=>t.id===id);}; function player(id){return players.find(p=>p.id===id);};
  async function load(){
    if(!sb)return;
    const [tx,tt,pp,mm,mp,gg]=await Promise.all([sb.from('tournaments').select('*').order('created_at',{ascending:true}).limit(1).maybeSingle(),sb.from('teams').select('*').order('name'),sb.from('players').select('*'),sb.from('matches').select('*').order('match_no'),sb.from('match_players').select('*'),sb.from('games').select('*')]);
    if(tx.error||tt.error||pp.error||mm.error||mp.error||gg.error){$('livePage').innerHTML=`<div class="card"><b>Unable to load live scores.</b></div>`;return;}
    tournament=tx.data; teams=tt.data||[]; players=pp.data||[]; $('title').textContent=tournament?.name||'PCBL Finals';
    const matches=(mm.data||[]).map(m=>{const gs=(gg.data||[]).filter(g=>g.match_id===m.id);const sideA=(mp.data||[]).filter(x=>x.match_id===m.id&&x.side==='A').map(x=>x.player_id);const sideB=(mp.data||[]).filter(x=>x.match_id===m.id&&x.side==='B').map(x=>x.player_id);return {...m,sideA,sideB,gs};}).filter(m=>m.status==='live'||m.status==='upcoming');
    $('livePage').innerHTML=matches.map(m=>{const a=team(m.team_a),b=team(m.team_b),g=m.gs.sort((x,y)=>x.game_no-y.game_no),cur=g.find(x=>!x.completed)||g[g.length-1]||{score_a:0,score_b:0};return `<div class="court"><div class="courthead"><div><b>Court ${esc(m.court||'—')}</b><div class="muted">${esc(m.match_type)} · ${esc(m.scheduled_at||'')}</div></div><span class="${m.status==='live'?'livepill':'status upcoming'}">${m.status==='live'?'● LIVE':'UPCOMING'}</span></div><div class="scoreteams"><div class="side"><div class="names"><b>${esc(a?.name||'—')}</b><br><small>${m.sideA.map(id=>esc(player(id)?.name||'')).join(' & ')}</small></div><div class="publicscore">${cur.score_a}</div></div><div class="center"><strong>–</strong><div class="games">Games ${g.filter(x=>x.completed&&x.score_a>x.score_b).length} : ${g.filter(x=>x.completed&&x.score_b>x.score_a).length}</div></div><div class="side"><div class="names"><b>${esc(b?.name||'—')}</b><br><small>${m.sideB.map(id=>esc(player(id)?.name||'')).join(' & ')}</small></div><div class="publicscore">${cur.score_b}</div></div></div></div>`;}).join('')||'<div class="card"><h2>No live matches</h2><p class="muted">The next fixtures will appear here.</p></div>';
  }
  if(window.supabase&&cfg.SUPABASE_URL&&cfg.SUPABASE_PUBLISHABLE_KEY){sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);load();sb.channel('public-live').on('postgres_changes',{event:'*',schema:'public',table:'matches'},load).on('postgres_changes',{event:'*',schema:'public',table:'games'},load).subscribe();}else{$('livePage').innerHTML='<div class="card"><b>Supabase configuration missing.</b></div>';}
})();
