(() => {
  const cfg = window.PCBL_CONFIG || {};
  let sb = null;
  let tournament = null, teams = [], players = [], matches = [], matchPlayers = [], games = [];
  const $ = id => document.getElementById(id);
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const team = id => teams.find(t => t.id === id);
  const player = id => players.find(p => p.id === id);
  const matchGames = id => games.filter(g => g.match_id === id).sort((a,b) => a.game_no-b.game_no);
  const matchType = m => m?.match_type || '';
  const isTriplet = m => matchType(m) === "Men's Triplet";
  const isQuad = m => matchType(m) === "Men's Quadruple";
  const isFinal = m => m?.stage === 'finals' || Number(m?.final_no) >= 1;
  const finalPoints = n => [1,3,5].includes(Number(n)) ? 15 : [2,4,6].includes(Number(n)) ? 60 : 21;
  const limit = m => isFinal(m) ? finalPoints(m.final_no) : isQuad(m) ? 60 : isTriplet(m) ? 30 : 21;
  function complete(m,a,b) {
    if(isFinal(m) || isQuad(m) || isTriplet(m)) return Math.max(a,b) >= limit(m);
    return (Math.max(a,b) >= 21 && Math.abs(a-b) >= 2) || Math.max(a,b) >= 30;
  }
  function winner(m) {
    const gs = matchGames(m.id);
    if(!gs.length) return null;
    const g=gs[0], a=Number(g.score_a||0), b=Number(g.score_b||0);
    return complete(m,a,b) && a!==b ? (a>b?m.team_a:m.team_b) : null;
  }
  function scoreText(m) { const gs=matchGames(m.id); if(!gs.length) return '—'; return gs.map(g=>`${g.score_a}-${g.score_b}`).join(' · '); }
  function orderedLineup(m,side){ return matchPlayers.filter(x=>x.match_id===m.id&&x.side===side).sort((a,b)=>(a.lineup_order??999)-(b.lineup_order??999)).map(x=>x.player_id); }
  function lineup(m,side){ const ids=orderedLineup(m,side); if(isQuad(m)&&ids.length>=4){const p=quadPhase(m), pairs=[[0,1],[1,2],[2,3],[3,0]][p-1]; return pairs.map(i=>player(ids[i])?.name).filter(Boolean).join(' + ') || '—';} if(isTriplet(m)&&ids.length>=3){const p=tripPhase(m);return (p===1?[ids[0],ids[1]]:[ids[1],ids[2]]).map(id=>player(id)?.name).filter(Boolean).join(' + ')||'—';} return ids.map(id=>player(id)?.name).filter(Boolean).join(' & ') || '—'; }
  function tripPhase(m){const g=matchGames(m.id)[0]||{};return (Number(g.score_a||0)+Number(g.score_b||0))<15?1:2;}
  function quadPhase(m){const g=matchGames(m.id)[0]||{};const high=Math.max(Number(g.score_a||0),Number(g.score_b||0));return high<15?1:high<30?2:high<45?3:4;}
  function finalLabel(n){const x=Number(n);return x===1?'Match 1 · Women’s Doubles':x===2?'Match 2 · Men’s Quadruple':x===3?'Match 3 · Men’s Singles':x===4?'Match 4 · Men’s Quadruple':x===5?'Match 5 · Women’s Doubles':x===6?'Match 6 · Men’s Quadruple':'Finals';}
  function formatTime(v){if(!v)return '—';const d=new Date(v);if(Number.isNaN(d.getTime()))return v;return d.toLocaleString([], {day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});}
  function resultForTeam(m,id){if(m.status!=='done')return m.status==='live'?'LIVE':'UPCOMING';const w=winner(m);return w===id?'WON':w?'LOST':'DRAW';}
  function teamDetailHtml(t){const ms=matches.filter(m=>m.team_a===t.id||m.team_b===t.id).sort((a,b)=>(a.match_no||0)-(b.match_no||0));const played=ms.filter(m=>m.status==='done'),wins=played.filter(m=>winner(m)===t.id).length,losses=played.filter(m=>winner(m)&&winner(m)!==t.id).length;const fixtures=ms.map(m=>{const isA=m.team_a===t.id,opp=team(isA?m.team_b:m.team_a),result=resultForTeam(m,t.id);return `<div class="team-fixture"><div class="fixture-main"><div><b>${esc(isFinal(m)?finalLabel(m.final_no):matchType(m))}</b><div class="muted">${esc(formatTime(m.scheduled_at))} · Court ${esc(m.court||'—')}</div></div><span class="status ${result==='WON'?'done':result==='LOST'?'live':result.toLowerCase()}">${result}</span></div><div class="fixture-vs"><b>${esc(t.name)}</b><span>vs</span><b>${esc(opp?.name||'—')}</b><strong>${esc(scoreText(m))}</strong></div><div class="fixture-players"><span>${esc(lineup(m,'A'))}</span><span>·</span><span>${esc(lineup(m,'B'))}</span></div></div>`;}).join('')||'<p class="muted">No fixtures assigned to this team yet.</p>';return `<div class="team-summary"><div><span>Players</span><b>${(t.players||[]).length}</b></div><div><span>Played</span><b>${played.length}</b></div><div><span>Wins</span><b>${wins}</b></div><div><span>Losses</span><b>${losses}</b></div></div><h3>Fixtures & Results</h3><div class="team-fixtures">${fixtures}</div>`;}
  function openTeamDetails(id){const t=team(id);if(!t)return;$('teamDetailTitle').textContent=`${t.name} — Fixtures & Results`;$('teamDetailBody').innerHTML=teamDetailHtml(t);$('teamDetailModal').classList.remove('hidden');}
  function show(page){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(page)?.classList.remove('hidden');document.querySelectorAll('#publicNav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));}
  function render(){
    $('tournamentTitle').textContent=tournament?.name||'PCBL 2026';
    $('tournamentMeta').textContent=[tournament?.venue,tournament?.status==='live'?'LIVE NOW':tournament?.status].filter(Boolean).join(' · ')||'Live badminton team-event results, standings and schedule.';
    $('stats').innerHTML=[['Teams',teams.length],['Players',players.length],['Matches',matches.length],['Live Courts',matches.filter(m=>m.status==='live').length]].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');
    const standing=teams.map(t=>({t,wins:matches.filter(m=>m.status==='done'&&winner(m)===t.id).length})).sort((a,b)=>b.wins-a.wins||a.t.name.localeCompare(b.t.name));
    $('standings').innerHTML=standing.map((x,i)=>`<button class="player standing-team" data-team-details="${esc(x.t.id)}"><span><b>${i+1}. ${esc(x.t.name)}</b><small>${(x.t.players||[]).length} players · ${matches.filter(m=>m.status==='done'&&(m.team_a===x.t.id||m.team_b===x.t.id)).length} played</small></span><b>${x.wins} win${x.wins===1?'':'s'}</b></button>`).join('')||'<p class="muted">No teams registered.</p>';
    $('schedule').innerHTML=matches.slice().sort((a,b)=>new Date(a.scheduled_at||0)-new Date(b.scheduled_at||0)).slice(0,12).map(m=>`<div class="player"><span><b>${esc(formatTime(m.scheduled_at))}</b> · Court ${esc(m.court||'—')}<br>${esc(isFinal(m)?finalLabel(m.final_no):matchType(m))} · ${esc(team(m.team_a)?.name||'—')} vs ${esc(team(m.team_b)?.name||'—')}</span><span class="status ${esc(m.status)}">${esc(m.status)}</span></div>`).join('')||'<p class="muted">No fixtures yet.</p>';
    $('liveGrid').innerHTML=matches.filter(m=>m.status==='live').map(courtHtml).join('')||'<div class="card"><h2>No live matches</h2><p class="muted">Live matches will appear here as soon as a scorer starts them.</p></div>';
    $('fixturesBody').innerHTML=matches.slice().sort((a,b)=>(a.match_no||0)-(b.match_no||0)).map(m=>`<tr><td>${esc(formatTime(m.scheduled_at))}</td><td>${esc(m.court||'—')}</td><td>${esc(isFinal(m)?finalLabel(m.final_no):matchType(m))}</td><td>${esc(team(m.team_a)?.name||'—')}<br><small>${esc(lineup(m,'A'))}</small></td><td>${esc(team(m.team_b)?.name||'—')}<br><small>${esc(lineup(m,'B'))}</small></td><td>${esc(lineup(m,'A'))} vs ${esc(lineup(m,'B'))}</td><td><span class="status ${esc(m.status)}">${esc(m.status)}</span></td><td><b>${esc(scoreText(m))}</b>${m.status==='done'&&winner(m)?`<br><small>Winner: ${esc(team(winner(m))?.name||'')}</small>`:''}</td></tr>`).join('')||'<tr><td colspan="8" class="muted">No fixtures yet.</td></tr>';
    $('teamCards').innerHTML=teams.map(t=>`<div class="teamcard"><div class="teamtitle"><h2>${esc(t.name)}</h2><span>${(t.players||[]).length} players</span></div><p class="muted">Captain: ${esc(t.captain||'—')}</p>${(t.players||[]).map(p=>`<div class="player"><span>${esc(p.name)}</span><span class="gender">${p.gender==='F'?'♀ Female':'♂ Male'}</span></div>`).join('')||'<p class="muted">No players registered.</p>'}</div>`).join('')||'<div class="card"><b>No teams yet.</b></div>';
  }
  function courtHtml(m){const a=team(m.team_a),b=team(m.team_b),g=matchGames(m.id)[0]||{score_a:0,score_b:0},sa=Number(g.score_a||0),sbx=Number(g.score_b||0),quad=isQuad(m),trip=isTriplet(m),final=isFinal(m);let banner='';if(quad){const p=quadPhase(m),idsA=orderedLineup(m,'A'),idsB=orderedLineup(m,'B'),ix=[[0,1],[1,2],[2,3],[3,0]][p-1];banner=`<div class="tripletPanel quadruplePanel"><div><b>${esc(a?.name||'—')}</b><small>${esc(idsA.map(id=>player(id)?.name||'').join(' · '))}</small></div><div class="tripletFlow"><b>ROTATION ${p} OF 4</b><span>${esc(ix.map(i=>player(idsA[i])?.name||'—').join(' + '))} vs ${esc(ix.map(i=>player(idsB[i])?.name||'—').join(' + '))}</span><small>Changes when either team reaches 15 / 30 / 45</small></div><div><b>${esc(b?.name||'—')}</b><small>${esc(idsB.map(id=>player(id)?.name||'').join(' · '))}</small></div></div>`;}const center=quad?`<div class="tripletPhase"><b>QUADRUPLE · 60 POINTS</b><span>ROTATION ${quadPhase(m)} · ${quadPhase(m)===1?'0–14':quadPhase(m)===2?'15–29':quadPhase(m)===3?'30–44':'45–59'}</span><small>Either team reaching the threshold changes both pairs</small></div>`:trip?`<div class="tripletPhase"><b>TRIPLET · 30 POINTS</b><span>PHASE ${tripPhase(m)} · ${tripPhase(m)===1?'0–15':'15–30'}</span></div>`:final?`<div class="games"><b>FINALS · ${limit(m)} POINTS</b><br>${esc(finalLabel(m.final_no))}</div>`:`<div class="games"><b>1 SET · 21 POINTS</b><br>Ends change at 11</div>`;return `<div class="court"><div class="courthead"><div><b>Court ${esc(m.court||'—')}</b><div class="muted">${esc(isFinal(m)?finalLabel(m.final_no):matchType(m))} · ${esc(formatTime(m.scheduled_at))}</div></div><span class="livepill">● LIVE</span></div>${banner}<div class="scoreteams"><div class="side"><div class="names"><b>${esc(a?.name||'—')}</b><br><small>${esc(lineup(m,'A'))}</small></div><div class="publicscore">${sa}</div></div><div class="center"><strong>–</strong>${center}</div><div class="side"><div class="names"><b>${esc(b?.name||'—')}</b><br><small>${esc(lineup(m,'B'))}</small></div><div class="publicscore">${sbx}</div></div></div></div>`;}
  async function load(){if(!sb)return;const [tx,tt,pp,mm,mp,gg]=await Promise.all([sb.from('tournaments').select('*').order('created_at',{ascending:true}).limit(1).maybeSingle(),sb.from('teams').select('*').order('name'),sb.from('players').select('*'),sb.from('matches').select('*').order('match_no'),sb.from('match_players').select('*'),sb.from('games').select('*')]);if(tt.error){$('connection').textContent='ERROR';$('connection').className='badge';return;}tournament=tx.data;teams=tt.data||[];players=pp.error?[]:(pp.data||[]);matches=mm.error?[]:(mm.data||[]);matchPlayers=mp.error?[]:(mp.data||[]);games=gg.error?[]:(gg.data||[]);teams=teams.map(t=>({...t,players:players.filter(p=>p.team_id===t.id)}));$('connection').textContent='LIVE';$('connection').className='badge ok';render();}
  if(!window.supabase||!cfg.SUPABASE_URL||!cfg.SUPABASE_PUBLISHABLE_KEY){$('connection').textContent='CONFIG ERROR';}else{sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);load();sb.channel('public-site').on('postgres_changes',{event:'*',schema:'public',table:'matches'},load).on('postgres_changes',{event:'*',schema:'public',table:'games'},load).on('postgres_changes',{event:'*',schema:'public',table:'teams'},load).on('postgres_changes',{event:'*',schema:'public',table:'players'},load).subscribe();}
  document.querySelectorAll('#publicNav button').forEach(b=>b.addEventListener('click',()=>show(b.dataset.page)));
  document.addEventListener('click',e=>{const btn=e.target.closest('[data-team-details]');if(btn)openTeamDetails(btn.dataset.teamDetails);if(e.target.id==='closeTeamDetail'||e.target.id==='teamDetailModal')$('teamDetailModal').classList.add('hidden');});
})();
